name: Release

env:
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

on:
  push:
    tags:
      - '*'

jobs:
  release-and-publish-package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Package and publish to Nuget📦
        run: |
          VERSION=`git describe --tags`
          echo "Publishing Version: ${VERSION}"
          npm install
          dotnet build
          rm -rf ./node_modules
          dotnet pack src/layout/src/AntDesign.ProLayout.csproj /p:PackageVersion=$VERSION -c Release -o publish
          dotnet nuget push publish/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
